baseURL: https://misha-aggarwal.netlify.app/
languageCode: en-us
title: Portfolio - Misha
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Currently interested in learning how judcious use of data can change the world.
      
    title: Misha's Portfolio Website
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Clarence Gate Gardens
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: maggarwal.mam2023@london.edu
    enable: yes
    phone:
      - phone: +44 74426 46089
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Misha
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/MishaAggarwal15
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/misha.aggarwal/
      - icon: fa-github
        label: GitHub
        url: https://github.com/mishaaggarwal15
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/misha-aggarwal
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    #subtitle: Misha's Portfolio Website
    title: Misha's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Learn more about me
        title: About me
        url: blogs/About_Misha
      - image: pic02.jpg
        subtitle: My Professional Journey
        title: CV
        url: blogs/MY_CV
      - image: cv.png
        subtitle:         
        title: My CV
        url: docs/MishaAggarwal.pdf
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Love to socialise and explore new cafes. Current student at LBS completing masters in Business and Analytics. Born and brought-up in India. 
    A certified yoga instructor and an active practioner. Looking forward to travel around Europe and explore my passions and interest!"
    title: Learn more about me
    url: blogs